### ISSUE TITLE
1.	Parser unable to detect the corrupted file.

### ISSUE THREAD

**Issue by sureshbaddipudi** [PA193/Parser-Project#1]
If you corrupt 3rd and 4th bytes of the image. The parser unable to parse the content of the file or it is unable to recognize the file is corrupted.

**Comment by PA193** [comment]
Closed issue by handling malformed input file via 6daec430a84790a4e18a37c5f029dd9418a0590d

**Comment by rktiff** [comment]
Code is refined again to give a provision for fuzzing through following commit
d8c79eb6e69cd4e0c6dfca4419a7f0c266a7dde5
