### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by sureshbaddipudi** [PA193/Parser-Project#2]
one variable ‘ret’ is assigned but not used.

**Comment by PA193** [comment]
Closed issue #2 by removing unused variable 'ret'  via 2aa39526759c0fcca827aa0bc9abea00920c39b1

**Comment by maxashwin** [comment]
The issue has been closed via d4e00e93ab3629f0a890e80b7138b72636038ba8
The unused variable ret was deleted and the issue resolved and closed.
