### ISSUE TITLE
Unable to fuzz

### ISSUE THREAD

**Issue by sureshbaddipudi** [PA193/Parser-Project#3]
Unable to fuzz, because the input is not a command line argument.

**Comment by PA193** [comment]
Closed issue by adding provision for command line input via 2f9120d8237799b7e6a1463973827f23283d2564

**Comment by rktiff** [comment]
Code is refined again to give a provision for fuzzing through following commit
d8c79eb6e69cd4e0c6dfca4419a7f0c266a7dde5
